from setuptools import setup

setup(
    name='backify',
    version='',
    packages=['lib', 'lib.job', 'lib.source', 'lib.storage', 'lib.configuration', 'test',
              'venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip.req', 'venv.lib.python2.7.site-packages.pip.vcs',
              'venv.lib.python2.7.site-packages.pip.utils', 'venv.lib.python2.7.site-packages.pip.compat',
              'venv.lib.python2.7.site-packages.pip.models', 'venv.lib.python2.7.site-packages.pip._vendor',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip.commands', 'venv.lib.python2.7.site-packages.pip.operations',
              'venv.lib.python2.7.site-packages.boto3', 'venv.lib.python2.7.site-packages.boto3.s3',
              'venv.lib.python2.7.site-packages.boto3.ec2', 'venv.lib.python2.7.site-packages.boto3.docs',
              'venv.lib.python2.7.site-packages.boto3.dynamodb', 'venv.lib.python2.7.site-packages.boto3.resources',
              'venv.lib.python2.7.site-packages.click', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.botocore', 'venv.lib.python2.7.site-packages.botocore.docs',
              'venv.lib.python2.7.site-packages.botocore.docs.bcdoc',
              'venv.lib.python2.7.site-packages.botocore.vendored',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.chardet',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.urllib3',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'venv.lib.python2.7.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.dateutil', 'venv.lib.python2.7.site-packages.dateutil.tz',
              'venv.lib.python2.7.site-packages.dateutil.zoneinfo', 'venv.lib.python2.7.site-packages.docutils',
              'venv.lib.python2.7.site-packages.docutils.utils', 'venv.lib.python2.7.site-packages.docutils.utils.math',
              'venv.lib.python2.7.site-packages.docutils.parsers',
              'venv.lib.python2.7.site-packages.docutils.parsers.rst',
              'venv.lib.python2.7.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python2.7.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python2.7.site-packages.docutils.readers', 'venv.lib.python2.7.site-packages.docutils.writers',
              'venv.lib.python2.7.site-packages.docutils.writers.xetex',
              'venv.lib.python2.7.site-packages.docutils.writers.latex2e',
              'venv.lib.python2.7.site-packages.docutils.writers.odf_odt',
              'venv.lib.python2.7.site-packages.docutils.writers.s5_html',
              'venv.lib.python2.7.site-packages.docutils.writers.pep_html',
              'venv.lib.python2.7.site-packages.docutils.writers.html4css1',
              'venv.lib.python2.7.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python2.7.site-packages.docutils.languages',
              'venv.lib.python2.7.site-packages.docutils.transforms', 'venv.lib.python2.7.site-packages.jmespath',
              'venv.lib.python2.7.site-packages.schedule', 'venv.lib.python2.7.site-packages.concurrent',
              'venv.lib.python2.7.site-packages.concurrent.futures', 'venv.lib.python2.7.site-packages.s3transfer',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='danstanhope',
    author_email='',
    description=''
)
